version: '3'
services:
  weather-api:
    build:
      context: . 
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - path: ./.env
        required: false

